const LOADING = 'LOADING';
const ERROR = 'ERROR';
const RESET_STATE = 'RESET_STATE';
const SET_DATA = 'SET_DATA';

const SET_DATA_FILTER = 'SET_DATA_FILTER';

export { ERROR, LOADING, RESET_STATE, SET_DATA, SET_DATA_FILTER };
